### ISSUE TITLE
question about the hardware integration

### ISSUE THREAD

**Issue by foxydevelby** [johnstonbrendan/Turtlebot_Jetson_Xavier_NX#1]
Hey ! great work!, can I use this as an inspiration with my project? 
 Can you share how did you supply your jetson board with turtlebot. ?

**Comment by johnstonbrendan** [comment]
Thanks. Of course you can use it as inspiration.
Not sure I fully understand your question, do you mean supply with power? 
If this is the case, I didn't power it off of the roomba base. I actually just had the default power cord hanging from the end hahaha. I did mention it in the things I wanted to add moving forward [here](https://github.com/johnstonbrendan/Turtlebot_Jetson_Xavier_NX#electrical).
